# Generated by Django 3.1.2 on 2021-07-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pubg_registered_id_tournament_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubg_registered_id',
            old_name='amount',
            new_name='pubg_id_1',
        ),
        migrations.RenameField(
            model_name='pubg_registered_id',
            old_name='phone_4_digit',
            new_name='pubg_id_2',
        ),
        migrations.RemoveField(
            model_name='pubg_registered_id',
            name='pubg_id',
        ),
        migrations.RemoveField(
            model_name='pubg_registered_id',
            name='transactionid',
        ),
    ]
