# Generated by Django 3.1.2 on 2021-07-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pubg_registered_id_10_taka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubg_registered_id_10_taka',
            name='tournament_name',
        ),
    ]
