# Generated by Django 3.1.2 on 2021-07-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_pubg_registered_id_10_taka_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubg_registered_id',
            name='phone_4_digit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pubg_registered_id',
            name='tournament',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pubg_registered_id',
            name='transactionid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pubg_registered_id',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pubg_registered_id',
            name='pubg_id_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pubg_registered_id',
            name='pubg_id_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pubg_registered_id',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
