# Generated by Django 3.1.2 on 2021-07-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210702_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubg_registered_id',
            name='registration_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
