# Generated by Django 3.1.2 on 2021-07-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pubg_registered_id_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubg_registered_id',
            name='room_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pubg_registered_id',
            name='room_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pubg_registered_id',
            name='slot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
