# Generated by Django 3.1.2 on 2021-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210702_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubg_registered_id',
            name='pubg_id_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
