# Generated by Django 3.1.2 on 2021-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210702_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubg_registered_id',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pubg_registered_id',
            name='phone_4_digit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pubg_registered_id',
            name='transactionid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
