# Generated by Django 3.1.2 on 2021-07-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210702_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubg_registered_id',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
