# Generated by Django 3.1.2 on 2021-07-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pubg_registered_id_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubg_registered_id',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2019-07-16'),
            preserve_default=False,
        ),
    ]
