# Generated by Django 3.1.2 on 2021-07-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210705_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubg_registered_id',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
