# Generated by Django 3.1.2 on 2021-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_pubg_registered_id_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='freefire_registered_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('tournament_name', models.CharField(max_length=100, null=True)),
                ('tournament', models.CharField(max_length=100, null=True)),
                ('freefire_id', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('transactionid', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_4_digit', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_status', models.CharField(max_length=100, null=True)),
                ('room_id', models.CharField(max_length=100, null=True)),
                ('room_password', models.CharField(max_length=100, null=True)),
                ('slot', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='pubg_registered_id',
            table='home_pubg_registered_id',
        ),
    ]
