# Generated by Django 3.1.2 on 2021-07-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210706_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freefire_registered_id',
            old_name='freefire_id',
            new_name='freefire_id_1',
        ),
        migrations.AddField(
            model_name='freefire_registered_id',
            name='freefire_id_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
