# Generated by Django 3.1.2 on 2021-07-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210707_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='freefire_registered_id',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
