# Generated by Django 3.1.2 on 2021-07-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_freefire_registered_id_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freefire_registered_id',
            name='freefire_id_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
